#!/bin/sh

# setup lte modem
uci set network.LTE=interface
uci set network.LTE.proto='mbim'
uci set network.LTE.device='/dev/cdc-wdm0'
uci set network.LTE.apn='internet'
uci set network.LTE.auth='none'
uci set network.LTE.pdptype='ipv4v6'

# USE public dns for router
uci add_list network.LTE.dns='8.8.8.8'
uci add_list network.LTE.dns='101.101.101.101'

# Final Commit
uci commit network

exit 0
