#!/bin/sh

# Enable Software Flow Offloading
uci set firewall.@defaults[0].flow_offloading='1'

# Enable Hardware Flow Offloading
# uci set firewall.@defaults[0].flow_offloading_hw='1'

# Final Commit
uci commit firewall
exit 0
