#!/bin/sh

# setup mac address
uci add network device
# uci set network.@device[-1]=device
uci set network.@device[-1].name='eth1'
uci set network.@device[-1].macaddr='<TARGET INTERFACE MAC ADDRESS>'

uci add network device
# uci set network.@device[-1]=device
uci set network.@device[-1].name='eth0'
uci set network.@device[-1].macaddr='<TARGET INTERFACE MAC ADDRESS>'

# Final commit
uci commit network
exit 0
